### ISSUE TITLE
Feature Request : Allow configuring number of parallel jobs

### ISSUE THREAD

**Issue by abdulkareemnalband** [kimmobrunfeldt/concurrently#175] opened 2018-10-29 07:14 UTC
## Feature Request

Limit number of parallel jobs to configurable option  like [`make`](https://linux.die.net/man/1/make)'s --jobs/-j option

## Expected Behavior 
There should be an option to configure number of parallel jobs

## Rationale
Running number of jobs more than cpu threads some times can can increase the amount of time required for jobs

**Comment by gustavohenke** [comment] 2018-10-29 12:23
Thanks for the request, @abdulkareemnalband! It sounds like a reasonable one 👍

**Comment by mtford90** [comment] 2019-01-31 14:57
Plus one to this - I had to search for a different solution after having crashed my computer a couple times - ideally i'd want to match the num. cpu cores.

**Comment by gustavohenke** [comment] 2020-01-27 09:14
Duplicate of #159

**Closed** 2020-02-10 11:48 UTC
Labels: enhancement

**Comment by gustavohenke** [comment] 2020-04-25 04:08
Published [`v5.2.0`](https://github.com/kimmobrunfeldt/concurrently/releases/tag/v5.2.0) with a `--max-processes` flag 🚢
