### ISSUE TITLE
Webpack progress output 

### ISSUE THREAD

**Issue by aaronbeall** [kimmobrunfeldt/concurrently#85] opened 2017-01-25 17:55 UTC
When I run webpack with `--progress` you get a line that updates with the current progress, like this:

```
"dev": "webpack-dev-server -d --inline --progress"
```

![webpack progress](http://g.recordit.co/YU5Vo7v8Lk.gif)

But when I run the command through `concurrently` the output puts every progress update on a new line, causing tons of output:

```
"dev-watch": "concurrently --kill-others \"npm run dev\" \"npm run css-watch\""
```

![concurrently progress](http://g.recordit.co/0yChrRPxVW.gif)

This happens on every small change so its pretty obnoxious. Is there a way to make the progress work as intended with `concurrently`?

**Comment by gustavohenke** [comment] 2017-01-26 00:21
Hmm, if I'm not mistaken, Webpack is using [the readline module](https://nodejs.org/dist/latest-v7.x/docs/api/readline.html) for this.

We'll need to find a way to work with this module, perhaps flagging each process as "readline"-able...

**Comment by aecz** [comment] 2017-02-09 10:44
Please check the issues, there is already an issue about this #2 and a PR #70 which is 3 months old by the way and no new comments :(

**Comment by pmowrer** [comment] 2017-03-29 20:31
Seems to work like expected if you pass the `raw` (`-r`) flag to `concurrently`

**Comment by aaronbeall** [comment] 2017-03-29 22:07
@pmowrer Nice, that works for me! Thanks

**Comment by aecz** [comment] 2017-03-30 14:52
With the `--raw` option you do not get the `prefixes `so no way of knowing which command wrote each line which almost defeats the purpose of using this package.
PR #70 solves this issue for non raw mode and #2 or this issue should be marked as duplicate.

**Comment by aaronbeall** [comment] 2017-03-30 18:20
@aecz The main reason I use `concurrently` is so I don't have to have multiple terminal tabs open. :) Is PR #70 going to be merged soon?

**Comment by leonardofaria** [comment] 2017-06-28 16:10
+1 curious to see this PR merged

**Comment by rickcnagy** [comment] 2017-07-07 18:26
I was having this issue when running `ng serve` (building and serving via Webpack in the [Angular CLI](https://github.com/angular/angular-cli)). Adding `--progress false` to `ng serve` worked without needing to add `--raw` to Concurrently:

```json
"start": "concurrently \"ng serve --progress false\""
```

+1 on #70 merging!

**Comment by wesamco** [comment] 2017-08-01 23:37
@gustavohenke @kimmobrunfeldt pls give this issue (#2/#85) the highest priority. thanks for making concurrently btw❤

here's my output case with the [Angular CLI](https://github.com/angular/angular-cli)
```
[0]   0% compiling
[0]  10% building modules 0/1 modules 1 active ...ten\src\backpage\app\app.component.ts
[0]  40% building modules 1/2 modules 1 active ...ten\src\backpage\app\app.component.ts
[0]  70% building modules 2/2 modules 0 active
[0]  71% sealing
[0]  75% advanced module optimization
[0]  76% basic chunk optimization pass 3
[0]  76% basic chunk optimization pass 4
[0]  78% advanced chunk optimization
[0]  80% module reviving                                                                                                                                                                                                       81% module order optimization
[0]  82% module id optimization
[0]  85% chunk id optimization
[0]  86% hashing
[0]  88% chunk assets processing
[0]  89% additional chunk assets processing
```

**Comment by aecz** [comment] 2017-08-02 10:31
@wesamco Did you try with #70 ? It is merged but not yet released and should fix the output. If yes, please provide more info to reproduce.

**Comment by filipesilva** [comment] 2017-08-02 10:40
@wesamco as an aside, you can use `--no-progress` to not get the progress report at all.

**Comment by fernandosouza** [comment] 2017-08-02 22:29
Hey, @aecz. #70 didn't solve the problem to me.

**Comment by aecz** [comment] 2017-08-03 09:13
@fernandosouza please post your steps to reproduce. You have an example in #70.

**Comment by fernandosouza** [comment] 2017-08-03 11:39
Hey, @aecz. I'm using webpack-dev-server and a tool that I've written to watch .soy files and compile them. I'm using both to create a hot reload since webpack doesn't know that .soy files exist.

This is the line I'm running: `"concurrently -k -r \"npm run soy:watch\" \"npm run start"`, where `npm run start` is `webpack-dev-server --open`

That causes a long webpack log as the issue mentions. But, during my debug, I realized that it can be a Webpack problem. I can reproduce the issue without concurrently, using only the `&` statement to call both npm tasks.

Sorry for the previous comment. I will let you know when I make sure where the problem is.

Thx.

**Comment by aaronjensen** [comment] 2017-10-13 06:35
FWIW, #70 fixed it for me. Any chance of a package release? Thanks!

**Comment by gustavohenke** [comment] 2017-11-21 01:05
Sorry for the delay on releasing this, folks! Check v3.5.1 🚢

**Closed by gustavohenke** 2017-11-21 01:05 UTC
Labels: enhancement

**Comment by wshamim** [comment] 2019-09-03 03:46
This issue is appearing again on latest version of Webpack (v4.32.0) and Concurrently (v4.1.2). 

Added (-r) seems to work fine with webpack.

**Comment by ryansully** [comment] 2019-09-23 23:02
Also seeing the issue reoccur with Webpack 4.40.2 and Concurrently 4.1.2.

While `-r` fixes the readline issue, it does also cause prefixes to disappear, and so isn't an ideal solution.

**Comment by aecz** [comment] 2019-09-24 09:43
@ryansully Could you check with concurrently version 3.5.1 ?

**Comment by swey** [comment] 2019-10-25 02:26
Yes, the problem exists again. Even with concurrently 3.5.1 and the latest webpack version.

**Comment by OliverJAsh** [comment] 2020-06-03 10:16
Does anyone have a workaround to this problem which doesn't result in losing prefixes (as is the case when using `--raw`)? The logs are really difficult to follow without those prefixes.

**Comment by OliverJAsh** [comment] 2020-06-03 12:16
Here is a reduced test case: https://github.com/OliverJAsh/webpack-concurrently

Can we re-open this issue?

**Comment by cben** [comment] 2020-06-03 14:07
I started playing with rewriting the prefixing code, but have nothing working yet.

What's the desired behavior when you have several children with progress output, say webpack and curl?
Or when webpack progress is mixed with regular lines from another child?

Obvious goals:
- progress \r lines should appear on output quickly.
- consecutive \r lines from same child should "collapse" together in final output.

But if let \r lines from different children overwrite each other on screen, the more chatty one will win and the less chatty ones will be mostly invisible.  Should we rate-limit "taking over the output"?

I'm also using concurrently in unattended CI, so I care how final "collapsed" output looks, and I'm not sure I want progress lines to disappear entirely.  I think ideally, I want a rate-limited subset of them to be retained as regular limes :thinking:

**Comment by cben** [comment] 2020-06-03 14:08
But I'll send something if I can get even the basic goal working.

**Comment by cben** [comment] 2020-10-21 17:50
Haven't made any significant progress on this :neutral_face:  Feel free to take over.

About webpack specifically: `webpack` CLI providid its own progress handler using `readline.clearLine` and `readline.cursorTo` until https://github.com/webpack/webpack-cli/pull/1772/files (not sure if `webpack-dev-server` was using that).  Now it's using the default logic from https://github.com/webpack/webpack/blob/5ff5c0d1cf6d3d491b5b54577d95a3bed71e23c7/lib/ProgressPlugin.js#L82-L83 which is using `logger.status` for disappearing messages, implemented in https://github.com/webpack/webpack/blob/master/lib/node/nodeConsole.js.
- It [shortens long lines with ... to avoid wrapping](https://github.com/webpack/webpack/blob/master/lib/logging/truncateArgs.js).
- Under a tty (`process.stderr.isTTY && process.env.TERM !== "dumb"`), it uses `\x1b[2K` "erase current line" escape sequence.  Without a tty, it just writes the colored lines as-is, without even \r, which means `concurrently` won't have any way to detect that these are progress lines :frowning:  https://github.com/webpack/webpack/issues/9769

**Comment by roryabraham** [comment] 2025-03-05 07:51
Would be great to reopen this issue, since it's still not addressed.

**Comment by gustavohenke** [comment] 2025-04-06 04:00
@roryabraham feel free to open a new one! Make sure to include a self-contained example repo.
