### ISSUE TITLE
Pass arguments

### ISSUE THREAD

**Issue by mellogarrett** [kimmobrunfeldt/concurrently#129] opened 2018-01-05 15:42 UTC
Is there a way to pass arguments to one of my concurrent scripts?

Ex: 
I have npm script of: `"serve": "concurrently \"npm run local\" \"http-server -p 8080\""`

I want to pass an argument to the second script, like this:
`npm run serve -- ./build`
but that results in this:
`concurrently "npm run local" "http-server -p 8080" "build"`
which causes an error...

**Comment by gustavohenke** [comment] 2018-01-28 03:01
Duplicate of #33

**Closed by gustavohenke** 2018-01-28 03:01 UTC
