### ISSUE TITLE
Limiting the amount of parallelism

### ISSUE THREAD

**Issue by joelzimmer** [kimmobrunfeldt/concurrently#159] opened 2018-08-06 19:27 UTC
How does `concurrently` decide how many processes to spawn? We have CI machines that have a lot of cores, but only have a small number available to work on. Can we limit the number of processes that are active at a given time?

**Comment by gustavohenke** [comment] 2018-08-19 16:01
Hello @joelzimmer,
Unfortunately there is no way to limit the parallelism. concurrently just spawns all of the passed commands at the same time.

However, I'm open to suggestions on how to tackle this, taking in consideration existing features such as restarting, killing other processes, etc.

**Comment by joelzimmer** [comment] 2018-08-19 22:50
@gustavohenke This is no longer a problem for us anymore (we're using slightly different build tactics in an upgraded system), but I'd look at [parallel-webpack](https://github.com/trivago/parallel-webpack) for inspiration - it'd be nice to pass in a limit of how many processes run and then queue which processes run.

**Comment by callumlocke** [comment] 2019-05-30 10:28
Another use case for this: temporarily setting the limit to 1 (i.e. to run all commands in series) while you're trying to debug something, to make it easier to read the stdout logs.

**Comment by gustavohenke** [comment] 2020-01-27 09:14
Duplicate of #175

**Closed** 2020-02-10 11:48 UTC
Labels: pending for input

**Comment by gustavohenke** [comment] 2020-04-25 04:08
Published [`v5.2.0`](https://github.com/kimmobrunfeldt/concurrently/releases/tag/v5.2.0) with a `--max-processes` flag 🚢
