### ISSUE TITLE
how to add suffix like --watch to each command?

### ISSUE THREAD

**Issue by veeramarni** [kimmobrunfeldt/concurrently#153] opened 2018-07-22 23:04 UTC
```
        "build": "npm run build:clean && npm run build:lib",
        "build:clean": "rimraf lib",
        "build:lib": "concurrently \"webpack --env.BUILD_FRONTEND\" \"webpack --env.BUILD_BACKEND\"",
        "build:lib:watch": "npm run build:lib -- --watch",

```

I was expecting the `build:lib:watch` to generate as 
```
"concurrently \"webpack --env.BUILD_FRONTEND --watch\" \"webpack --env.BUILD_BACKEND --watch\""
```

**Comment by gustavohenke** [comment] 2018-07-24 12:07
Duplicate of #33

**Closed by gustavohenke** 2018-07-24 12:07 UTC
